name: Update Recent Activity

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:          # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update README with recent activity
        uses: Readme-Workflows/recent-activity@v2
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token is auto-provided
          MAX_LINES: 10                         # Show latest 10 activities
